name: 'Lint and Format'
run-name: ${{ github.actor }} is linting and checking formatting
on:
  pull_request:
jobs:
  run-linter:
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/jod
      - run: npm ci --legacy-peer-deps
      - run: npm run lint
      - run: npm run format:check
